### ISSUE TITLE
ModuleNotFoundError: No module named '_curses'

### ISSUE THREAD

**Issue by jegor377** [carlosmaniero/pygamii#6]
E:\Python\pygamii\examples\arkanoid>main.py
Traceback (most recent call last):
  File "E:\Projekty\Python\pygamii\examples\arkanoid\main.py", line 3, in <module>
    from pygamii.scene import BaseScene
  File "E:\Python\lib\site-packages\pygamii-0.0.1.4-py3.6.egg\pygamii\scene.py", line 3, in <module>
    from pygamii.utils import get_color_pair
  File "E:\Python\lib\site-packages\pygamii-0.0.1.4-py3.6.egg\pygamii\utils.py", line 2, in <module>
    import curses
  File "E:\Python\lib\curses\__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'

**Comment by sudox** [comment]
Looks like you're trying to run it on Windows and the Windows version of python doesn't have access to Curses. You might be able to get it working by following the steps listed here https://stackoverflow.com/questions/32417379/what-is-needed-for-curses-in-python-3-4-on-windows7

**Comment by Aareon** [comment]
https://github.com/zephyrproject-rtos/windows-curses

This would fix this issue.
`pip install windows-curses --user`

**Comment by jegor377** [comment]
@Aareon thanks! Unfortunately I don't remember if I fix the issue or not, because it was long time ago. I will close the issue. I'm not able to check if it'll work.
